# (PART) 雨苗 {#yumiao .unnumbered} 

# 同桌的你 {#classmates .unnumbered}

京生班有个女同学叫莱提西娅，意大利女孩，长得很漂亮，有一双明亮的蓝色大眼睛。漂亮姑娘总是男生缘超好，经常是男生生日会上就她一个女生，在一群男孩子中特别显眼。

忘记什么原因，京生妈和美女妈妈成了朋友，两个孩子之间的联系也多了起来。作为外援，京生陪着小美女和她的妈妈和妹妹一起看电影; 小美女经常打电话过来问京生作业的事情。我们一起去了乐高王国主题公园玩，还有两个孩子玩机械手臂的合影。京生爸爸看了他们的合照，酸酸地说：“儿子将来泡妞一定比我厉害！”

上周五，京生在回家路上高兴地给我唱他自己编的歌，唱到一半，歌词里冒出了“莱提西娅”这个名字，我问他： “你这首歌是写给莱提西娅的？”
> 
> “当然是啊！”

小伙子眨眨眼睛，笑着对我说。

京生啊，你还记得大明湖畔苦苦等你的香雨荷吗？

貌似兄弟俩总是心心相通，德生最近嘴边也总念叨着一个姑娘的名字，叫汉娜。动不动就说：

> “我喜欢汉娜，我要给汉娜打电话。”

然后拿起哥哥的橡皮手机，拨号：

> “1，2，3，4，5......喂，汉娜，我们一起玩儿吧。好的，再见，拜拜！”

我和娃爹在一旁听得呆了。

某天我早上送娃去托儿所，小朋友们正在桌边准备吃早饭。见德生一进来，一个小姑娘大叫着“德生！”就从桌上跳了下来直奔德生，两个小孩子跑到一起，就面对面甜甜地笑了。


原来，她就是汉娜。

# 人见人爱的小F {#flori .unnumbered}

京生的同学小F，是个人见人爱的男孩子。

他长得比同龄人小，脸上挂着婴儿肥。而且很聪明伶俐，老师和同学们都很喜欢他。


同学小J，不管任何时候，只要一见到小F，就会马上大叫着冲过来紧紧抱住他。“哦小F，你好可爱好可爱啊！”甩都甩不掉。


去参加同学小L的生日会，小L的哥哥听说小F很可爱，特意跑过来抱抱他，摸摸他的头，捏捏他的脸蛋，说“哇，你真的好可爱啊！”


学校狂欢节，小朋友们可以打扮成喜欢的样子来小学。小F说他要打扮成一只老鼠。结果到了狂欢节当天，同学小K特意扮成一只猫，一进到教室就开始追着他满屋子跑。


学校体育课要玩一种运动，类似于我们小时候玩的丢沙包，同学分成两队，场下队分站两边，互相扔球直到把场上队员打下来为止。因为小F太可爱了，所以大家总是第一个把他打下来。所以，他的体育课大部分时间是在冷板凳上坐着，看大家玩儿。


某天放学回来，京生兴奋的说：“妈妈，莱提西娅写了一首给小F的歌！”


我暗暗叹了口气，小学生的情感世界还挺丰富。“那歌的名字叫什么呢？”我问道。


京生更加兴奋的说：“歌的名字叫， 《小F，死了！》”


……


一时间，我觉得小学生的世界也挺暗黑的。