# (PART) zouxiang {#zouxiang .unnumbered} 

# 家里有个“挑食”娃 {#food-picking .unnumbered}

这题目大家会以为是写怎么治理家里宝宝的挑食，事实却是本人是那个恼人的“挑食”娃。最近，我以子女的身份回顾了一下我经历的家庭生活，确实发现一些值得为人父母的我反思和谨慎的地方，希望分享给各位正在成长的父母。

我原以为像我和我妈这样波澜不惊的母女关系，不会有什么大不了的事情，可如今细细回想，我性格中“倔”得气人的成分大概就是从其中演化而来的。我是我妈眼中挑食得不得了的孩子，我不吃的有哪些食物呢，葱、姜、蒜、香菜、肥肉、动物内脏。我自己觉得不吃这些东西是很合理的，相信我的同类并不在少数。但我妈做菜一定会放葱、姜、蒜，包饺子除了韭菜鸡蛋馅，其他都会放肥肉。所以在我妈看来，我是个不爱吃菜，不爱吃饺子的孩子，饺子只吃韭菜鸡蛋馅，能不叫“挑食”嘛，要不怎么这么瘦小。因为“挑食”而且瘦小，这简直是必然的，我看过很多中医，喝过很多汤药，我妈还很好奇，这孩子药都肯喝，怎么就不吃饭呢，饭之于我真的是怪味道。小时候的我也说不出其中缘由，我以为这世界饭就这样呢。我当然去过亲戚家还有邻居家吃饭，吃得很香，我妈归因于小孩子都是吃别人家的饭香。我妈也有维护自己观点的证据，那就是我姐姐吃她做的饭没问题啊，是啊，因为我姐可以吃葱、姜、蒜、香菜和肥肉馅的饺子。就这样问题一定出在我身上。想想本来是件小事儿，可这么一天天的饭吃的像受刑一样，我心里是恐惧吃饭的，我得挑出菜里的葱、姜、蒜，还有饺子里的肥肉，所以我索性吃很少的菜，只吃米饭，饺子就只吃皮。这就是一度我的饮食状况。

等我可以明确要求不要放葱、姜、蒜、香菜，而我妈还是肯定会放的时候，我是很烦躁又无奈的。我和我妈的吵架多半情况都被我妈归因于我的“倔”，但我现在想来，那些冲突都是饭菜这个问题积蓄的负面情绪由不同导火索引爆了而已。如今想来也觉得不可思议，十几年我妈都想改变我不吃葱、姜、蒜、香菜、肥肉的现实，她的想法是切碎一些，或者包在馅儿里，我一不留神就吃了。我的味觉排斥这些东西，真没有不留神的时候，我不小心吃到，真是整口饭都要吐的。其实我妈应该理解这种不吃某种食物的感受，她说她年轻时候不吃羊肉，后来上大学吃了涮羊肉以后就开始吃了。于是她一直在试我可以转变的那个时点。三十年过去了，我还是没有转变。现在我和我妈一起生活的时候很少了，偶尔吃她做的饭，她会说这菜特意没有放葱、姜、蒜，但也不是每次，还是多数时候会放。我有时候会想，是不是正因为我不吃，我妈才这么执着要放呢。我的世界不理解，不放葱、姜、蒜就那么难操作吗？

多么小的一件事啊，就是无法和解。

我现在守着一岁八个月的闺女，真心体会到做母亲的不容易，但我也告诫自己不要重蹈那些不必要的覆辙。尊重她的个性，像三餐这种最平常却潜移默化影响深远的机会要多多重视，以此让她体会到满满的爱。用心，不易，但收获所在或许出乎意料。